#!/usr/bin/env python3
"""Bakes outputs/metrics.csv and outputs/arm_benchmark.json into
docs/dashboard.html so it can be opened directly in a browser with no
server, no fetch(), and no CORS issues.

Usage:
    python scripts/run_scenarios.py --out outputs/metrics.csv
    python -m bhs.optimize.benchmark --out outputs/arm_benchmark.json
    python scripts/build_dashboard.py
"""
import csv
import json
import os

BASE = os.path.join(os.path.dirname(__file__), "..")
METRICS_CSV = os.path.join(BASE, "outputs", "metrics.csv")
BENCHMARK_JSON = os.path.join(BASE, "outputs", "arm_benchmark.json")
OUT_HTML = os.path.join(BASE, "docs", "dashboard.html")

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Black Dragon Optical Skin -- Results Dashboard</title>
<style>
  :root { color-scheme: dark; }
  body { background:#0b0f14; color:#e6edf3; font-family: -apple-system, Segoe UI, sans-serif; margin:0; padding:24px; }
  h1 { font-size: 22px; margin-bottom:4px; }
  h2 { font-size:16px; color:#9fb3c8; margin-top:36px; }
  .sub { color:#8899a6; margin-bottom:24px; }
  table { border-collapse: collapse; width:100%; margin-bottom:8px; font-size:13px; }
  th, td { border:1px solid #22303c; padding:6px 10px; text-align:right; }
  th { background:#111a22; text-align:right; }
  td:first-child, th:first-child { text-align:left; }
  .system-bhs { color:#5ee3a0; font-weight:600; }
  .system-baseline { color:#f2b84b; }
  .system-unmitigated { color:#f26a6a; }
  .bars { display:flex; flex-direction:column; gap:6px; margin-top:8px;}
  .bar-row { display:flex; align-items:center; gap:8px; font-size:12px; }
  .bar-label { width:160px; color:#9fb3c8; }
  .bar-track { flex:1; background:#111a22; border-radius:4px; overflow:hidden; height:16px; }
  .bar-fill { height:100%; }
  .note { color:#8899a6; font-size:12px; margin-top:24px; }
  code { background:#111a22; padding:1px 5px; border-radius:3px; }
</style>
</head>
<body>
<h1>Black Dragon Runtime</h1>
<div class="sub" style="font-size:15px;color:#5ee3a0;margin-bottom:4px;">The world's first Distributed Industrial Nervous System, optimized for Arm</div>
<div class="sub">Generated by <code>scripts/build_dashboard.py</code> from <code>outputs/metrics.csv</code> and <code>outputs/arm_benchmark.json</code>. Re-run the pipeline to refresh with your own numbers. See also <code>NPU_PIPELINE.md</code> (real Ethos-U NPU compile) and <code>REFLEX_KERNEL_BENCHMARK.md</code> (polling vs interrupt vs reflex kernel) and <code>docs/optical_skin_demo.html</code> (live interactive demo).</div>

<h2>Scenario metrics: BHS vs. fixed point-sensor baseline vs. unmitigated</h2>
<table id="metrics-table"></table>
<div id="damage-bars" class="bars"></div>

<h2>Arm-optimization benchmark (reflex kernel hot loop)</h2>
<table id="bench-table"></table>
<div class="note" id="bench-platform"></div>

<div class="note">
See <code>ARM_OPTIMIZATION.md</code> for the full write-up, including how to
re-run this benchmark on real Arm64 hardware (Raspberry Pi / AWS Graviton /
Docker buildx --platform linux/arm64) and with Arm Performix.
</div>

<script>
const metrics = __METRICS_JSON__;
const bench = __BENCH_JSON__;

function renderMetrics() {
  const cols = ["scenario","system","detect_time_s","predict_lead_time_s",
                "localization_error_cells","damage_prevented_pct",
                "reaction_latency_s","wallclock_per_step_ms"];
  const labels = {
    scenario: "Scenario", system: "System", detect_time_s: "Detect (s)",
    predict_lead_time_s: "Predict lead (s)", localization_error_cells: "Localization err (cells)",
    damage_prevented_pct: "Damage prevented (%)", reaction_latency_s: "Reaction latency (s)",
    wallclock_per_step_ms: "ms / step"
  };
  let html = "<tr>" + cols.map(c => `<th>${labels[c]}</th>`).join("") + "</tr>";
  for (const row of metrics) {
    html += `<tr class="system-${row.system}">` + cols.map(c => {
      let v = row[c];
      if (v === "" || v === undefined) v = "&mdash;";
      else if (typeof v === "string" && !isNaN(parseFloat(v)) && c !== "scenario" && c !== "system") {
        v = parseFloat(v).toFixed(2);
      }
      return `<td>${v}</td>`;
    }).join("") + "</tr>";
  }
  document.getElementById("metrics-table").innerHTML = html;

  const colors = { bhs: "#5ee3a0", baseline: "#f2b84b", unmitigated: "#f26a6a" };
  let barsHtml = "";
  for (const row of metrics) {
    const pct = Math.max(0, Math.min(100, parseFloat(row.damage_prevented_pct) || 0));
    barsHtml += `<div class="bar-row"><div class="bar-label">${row.scenario} / ${row.system}</div>
      <div class="bar-track"><div class="bar-fill" style="width:${pct}%;background:${colors[row.system]}"></div></div>
      <div>${pct.toFixed(1)}%</div></div>`;
  }
  document.getElementById("damage-bars").innerHTML = "<h3 style='font-size:13px;color:#9fb3c8;'>Damage prevented vs. unmitigated</h3>" + barsHtml;
}

function renderBench() {
  if (!bench || !bench.results) return;
  let html = "<tr><th>Implementation</th><th>ms / step</th><th>State bytes</th><th>Agreement vs f64</th><th>Speedup vs f64</th></tr>";
  for (const r of bench.results) {
    html += `<tr><td>${r.name}</td><td>${r.mean_ms_per_step.toFixed(4)}</td><td>${r.state_bytes.toLocaleString()}</td><td>${(r.agreement_vs_f64*100).toFixed(1)}%</td><td>${r.speedup_vs_f64.toFixed(2)}x</td></tr>`;
  }
  document.getElementById("bench-table").innerHTML = html;
  document.getElementById("bench-platform").innerText =
    "Collected on: " + JSON.stringify(bench.platform);
}

renderMetrics();
renderBench();
</script>
</body>
</html>
"""


def main():
    if not os.path.exists(METRICS_CSV):
        raise SystemExit(f"Missing {METRICS_CSV}. Run scripts/run_scenarios.py first.")

    with open(METRICS_CSV) as f:
        metrics = list(csv.DictReader(f))

    bench = None
    if os.path.exists(BENCHMARK_JSON):
        with open(BENCHMARK_JSON) as f:
            bench = json.load(f)

    html = TEMPLATE.replace("__METRICS_JSON__", json.dumps(metrics))
    html = html.replace("__BENCH_JSON__", json.dumps(bench))

    os.makedirs(os.path.dirname(OUT_HTML), exist_ok=True)
    with open(OUT_HTML, "w") as f:
        f.write(html)
    print(f"Wrote {OUT_HTML}")


if __name__ == "__main__":
    main()
